# Makefile for DFET (Linux CLI Version)
#
# --- USAGE ---
# make            -> Builds/updates the optimized release version.
# make release    -> Explicitly builds/updates the optimized release version.
# make debug      -> Builds/updates the unoptimized version with debug symbols.
# make clean      -> Removes all generated build artifacts for all build types.

# --- Compiler and Core Settings ---
CXX = g++
TARGET_NAME = dfet

# Recursively find all C++ source files.
SRCS := $(shell find . -name "*.cpp")

# --- Common Configuration ---
INCLUDE_PATHS = -I./ -Ilibs/DFfile -Ilibs/DFfile/DFset
LINK_LIBS = -lstdc++fs
# Base flags, common to both release and debug builds
BASE_CXXFLAGS = -std=c++17 -Wno-narrowing -DDFET_CLI_MODE

# --- Release Build Configuration ---
RELEASE_DIR = build/release
RELEASE_OBJ_DIR = $(RELEASE_DIR)/obj
RELEASE_TARGET = $(RELEASE_DIR)/$(TARGET_NAME)
RELEASE_CXXFLAGS = -O2
# Define where the object files for the release build will be created
RELEASE_OBJS := $(patsubst %.cpp,$(RELEASE_OBJ_DIR)/%.o,$(SRCS))

# --- Debug Build Configuration ---
DEBUG_DIR = build/debug
DEBUG_OBJ_DIR = $(DEBUG_DIR)/obj
DEBUG_TARGET = $(DEBUG_DIR)/$(TARGET_NAME)
DEBUG_CXXFLAGS = -g -O0
# Define where the object files for the debug build will be created
DEBUG_OBJS := $(patsubst %.cpp,$(DEBUG_OBJ_DIR)/%.o,$(SRCS))


# --- Build Rules ---

# Phony targets are not files.
.PHONY: all release debug clean

# The default target, executed when you just run 'make'.
all: release

# Public-facing targets. These depend on the actual executable file.
release: $(RELEASE_TARGET)
debug: $(DEBUG_TARGET)

# --- Linking Rules ---

# Rule to link the final release executable.
$(RELEASE_TARGET): $(RELEASE_OBJS)
	@echo "Linking Release Target..."
	@mkdir -p $(@D)
	$(CXX) $^ -o $@ $(LINK_LIBS)
	@echo "Release build complete. Executable is '$@'."

# Rule to link the final debug executable.
$(DEBUG_TARGET): $(DEBUG_OBJS)
	@echo "Linking Debug Target..."
	@mkdir -p $(@D)
	$(CXX) $^ -o $@ $(LINK_LIBS)
	@echo "Debug build complete. Executable is '$@'."


# --- Compilation Rules ---

# Generic rule for compiling release object files.
# It creates dependency files (.d) to track header changes.
$(RELEASE_OBJ_DIR)/%.o: %.cpp
	@echo "Compiling [Release] $<"
	@mkdir -p $(@D)
	$(CXX) $(BASE_CXXFLAGS) $(RELEASE_CXXFLAGS) $(INCLUDE_PATHS) -MMD -MP -c $< -o $@

# Generic rule for compiling debug object files.
$(DEBUG_OBJ_DIR)/%.o: %.cpp
	@echo "Compiling [Debug] $<"
	@mkdir -p $(@D)
	$(CXX) $(BASE_CXXFLAGS) $(DEBUG_CXXFLAGS) $(INCLUDE_PATHS) -MMD -MP -c $< -o $@


# --- Cleanup Rule ---
# This rule is safer than 'rm -rf build'. It only removes the directories
# that are generated by this Makefile, leaving any other files or directories
# in the 'build' folder untouched.
clean:
	@echo "Cleaning up build artifacts..."
	@rm -rf $(RELEASE_DIR) $(DEBUG_DIR)
	@echo "Cleanup complete."


# --- Dependency Inclusion ---
# Include all the generated dependency files.
# The '-' suppresses errors if the files don't exist yet.
-include $(RELEASE_OBJS:.o=.d)
-include $(DEBUG_OBJS:.o=.d)
